name: Export Secrets
on:
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export secrets
        run: |
          echo "WIRE_URL=${{ secrets.WIRE_URL }}" >> $GITHUB_ENV
